### ISSUE TITLE
Minimum Players to start

### ISSUE THREAD

**Issue by barmosa** [B3none/cs2-retakes#144] opened 2024-11-09 11:30 UTC
Hi, can you add an option of at least two players to start the retakes?
And if there is only one player wurmap will be eternal until there are 2+ players on the server

**Comment by B3none** [comment] 2024-11-09 11:36
Duplicate of #124

**Closed by B3none** 2024-11-09 11:36 UTC

**Comment by B3none** [comment] 2024-11-09 11:40
Also duplicate of #109
